# Generated by Django 3.2.6 on 2023-01-04 18:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='Введите свое имя', max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите свою фамилию', max_length=20, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите свой номер телефона', max_length=128, region=None, unique=True, verbose_name='номер телефона')),
                ('email', models.EmailField(help_text='Введите свой адрес эл. почты', max_length=254, unique=True, verbose_name='адрес эл. почты')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', help_text='Выберите роль пользователя', max_length=5, verbose_name='Роль пользователя')),
                ('image', models.ImageField(blank=True, help_text='Загрузите вашу фотографию', null=True, upload_to='photos/', verbose_name='Фото')),
                ('is_active', models.BooleanField(help_text='Укажите, активен ли ваш аккаунт', verbose_name='Активен ли аккаунт')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
